name: Terraform

on:

  # Feature branch par push hote hi PLAN chalega
  push:
    branches:
      - "**"

  # Pull Request to main
  pull_request:
    branches:
      - main

  # Manually run workflow
  workflow_dispatch:


jobs:

  terraform:

    name: Terraform
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4


      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # 3. Azure Login
      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "efa612e2-52ae-4608-adaf-e792898d130b" \
            --password "s6T8Q~YomF6Kc_iISy~4VXwpKXG5UIWAk0V5gbtk" \
            --tenant "c19495c3-7313-414d-bf97-f60a4fbc2c0d"


      # 4. Set Azure Subscription
      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "9d42e269-3739-4811-a09c-a7fe1e4e9c7a"


      # 5. Check Azure Account
      - name: Azure Account
        run: |
          az account show


      # 6. Terraform Init
      - name: Terraform Init
        working-directory: environment/dev
        run: terraform init


      # 7. Terraform Format
      - name: Terraform Format
        working-directory: environment/dev
        run: terraform fmt -check -recursive


      # 8. Terraform Validate
      - name: Terraform Validate
        working-directory: environment/dev
        run: terraform validate


      # 9. Terraform Plan
      # Feature branch + Pull Request par PLAN
      - name: Terraform Plan
        run: |
          terraform plan
        working-directory: environment/dev
        

      # 10. Terraform Apply
      # APPLY sirf main branch par
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve
        working-directory: environment/dev